name: Build release APK and publish Github release

on:
  # Trigger by pushing a version tag (which are protected)
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get version name from git tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION

      - name: Assemble F-Droid APK
        run: ./gradlew assembleFdroidRelease --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign APK
        uses: r0adkll/sign-android-release@dbeba6b98a60b0fd540c02443c7f428cdedf0e7f # v1.0.4
        id: sign_apk
        with:
          releaseDirectory: app/build/outputs/apk/fdroid/release
          signingKeyBase64: ${{ secrets.APK_SIGNING_KEYSTORE_FILE }}
          alias: release
          keyStorePassword: ${{ secrets.APK_SIGNING_KEYSTORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Rename APK file
        run: mv ${{steps.sign_apk.outputs.signedReleaseFile}} orgzly-revived-fork-${{ env.VERSION }}.apk

      - name: Create Github release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: orgzly-revived-fork-${{ env.VERSION }}.apk
          draft: false
          body: |
            This is a personal fork of [Orgzly Revived](https://github.com/orgzly-revived/orgzly-android-revived), maintained by [@amarder](https://github.com/amarder).

            Install or auto-update it with [Obtainium](https://github.com/ImranR98/Obtainium) by adding this repository, or download the APK below directly.
